# Generated by Django 5.0.4 on 2024-05-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
